import numpy as np

START_MARKER = b'rbn'
SAMPLE_RATE = 48_000
TEST_WAV = 'test.wav'
FREQ_BASE = 512
FREQ_SPACE = 16
OUTPUT_MAX = np.iinfo(np.int16).max
DO_COMPRESS = False
TONES_PER_SECOND = 16
TONE_BITS = 8
OUTPUT_SURROUNDING_NOISE_SECONDS = 0.1
OUTPUT_SURROUNDING_NOISE_LEVEL = 1e3
