import numpy as np

START_MARKER = b'rbn'
SAMPLE_RATE = 48_000
TEST_WAV = 'test.wav'
FREQ_BASE = 512
FREQ_SPACE = 32
OUTPUT_MAX = np.iinfo(np.int16).max
DO_COMPRESS = False
TONES_PER_SECOND = 8
TONE_BITS = 8

OUTPUT_SURROUNDING_NOISE_SECONDS = 1
OUTPUT_SURROUNDING_NOISE_LEVEL = 1e5
INPUT_PRE_NOISE_LEVEL = 2e3

ANTICLICK_STOP_AT_FULL_PERIOD = True
ANTICLICK_FADE = True
ANTICLICK_FADE_AMOUNT = 16  # 16 means 1/16th of a tone used for fade-in and fade-out
