import numpy as np

START_MARKER = b'rbn'
SAMPLE_RATE = 48_000
TEST_WAV = 'test.wav'
FREQ_BASE = 512
FREQ_SPACE = 64
# FREQ_EXP_BASE = 1.5
OUTPUT_MAX = np.iinfo(np.int16).max
DO_COMPRESS = False
TONES_PER_SECOND = 3
TONE_BITS = 4
SAMPLES_PER_TONE = SAMPLE_RATE // TONES_PER_SECOND

OUTPUT_PRE_NOISE_SECONDS = 1
OUTPUT_PRE_NOISE_LEVEL = 1e5
INPUT_PRE_NOISE_LEVEL = 1e3

ANTICLICK_STOP_AT_FULL_PERIOD = True
ANTICLICK_FADE = True
ANTICLICK_FADE_AMOUNT = 16  # 16 means 1/16th of a tone used for fade-in and fade-out

RECORD_CHUNK_SIZE = 1
RECORD_BUFFER_SIZE = 128*1024
RECORD_PROCESS_INTERVAL = 0.5
